FROM ubuntu:22.04
RUN apt-get update && \
    apt-get install -y --no-install-recommends galera-arbitrator-4 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
COPY scripts/garbd-entrypoint.sh /garbd-entrypoint.sh
ENTRYPOINT ["/garbd-entrypoint.sh"]
